### ISSUE TITLE
Todo's 11.02.2021

### ISSUE THREAD

**Issue by DerAlexx** [DerAlexx/HMCoin#11]
Todos:

- [x] PowerPoint Abschlusspräsentation
- [x] Issues durchgehen/aktualiseren
- [x] Frontend fertigstellen
- [x] Proof-of-Work einbauen Frontend
- [x] Proof-of-Work einbauen Backend
