### ISSUE TITLE
Todo's 10.02.2021

### ISSUE THREAD

**Issue by DerAlexx** [DerAlexx/HMCoin#13]
- [x] Doku REST-API
- [x] Proof-of-Work - Konzept
- [x] Proof-of-Work Doku 
- [x] Frontend weitermachen
- [x] Issues Donnerstag
