### ISSUE TITLE
Todo's 03.02 und 04.02

### ISSUE THREAD

**Issue by DerAlexx** [DerAlexx/HMCoin#6]
- [x] Doku Projektbauen
- [x] Doku Projektstarten
- [x] Doku Projektstruktur
- [x] Backend REST-API (Teil I)
- [x] ReadMe Projektbeschreibung
- [x] ReadMe Architektur
- [x] Frontend ausbauen.
- [x] Issues für Freitag
- [x] PowerPoint Pitch Freitag
